load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "path",
    srcs = ["path.go"],
    importpath = "github.com/nacl2000/clould_storage/tools/path",
    visibility = ["//visibility:public"],
)
